### ISSUE TITLE
When setting log level to error, adapter restarts in loop

### ISSUE THREAD

**Issue by thesnoopy** [iobroker-community-adapters/ioBroker.roomba#184]
As mentiond in the subject, as soon as I set the log level to ERROR the adapter goes into a restart loop. Log below:

2024-04-05 09:28:12.169  - [32minfo[39m: roomba.0 (9252) starting. Version 1.2.2 in /opt/iobroker/node_modules/iobroker.roomba, node: v18.20.1, js-controller: 5.0.19
2024-04-05 09:28:12.191  - [32minfo[39m: roomba.0 (9252) Connecting to Roomba (172.16.29.23)..
2024-04-05 09:28:12.284  - [32minfo[39m: roomba.0 (9252) Restored last mission (#2505).
2024-04-05 09:28:15.529  - [32minfo[39m: roomba.0 (9252) Roomba online. Connection established.
2024-04-05 09:28:15.531  - [32minfo[39m: roomba.0 (9252) State value to set for "roomba.0.states._connected" has to be type "string" but received type "boolean" 
2024-04-05 09:28:16.330  - [32minfo[39m: roomba.0 (9252) Roomba has resumed a previous mission (#2505).
2024-04-05 09:28:16.335  - [31merror[39m: roomba.0 (9252) uncaught exception: Cannot read properties of undefined (reading 'theta')
2024-04-05 09:28:16.336  - [31merror[39m: roomba.0 (9252) TypeError: Cannot read properties of undefined (reading 'theta')
    at mapMission (/opt/iobroker/node_modules/iobroker.roomba/roomba.js:720:51)
    at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roomba/roomba.js:363:6)
    at MqttClient.emit (node:events:517:28)
    at Timeout._onTimeout (/opt/iobroker/node_modules/@karlvr/dorita980/lib/v2/local.js:48:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
2024-04-05 09:28:16.336  - [31merror[39m: roomba.0 (9252) Cannot read properties of undefined (reading 'theta')
2024-04-05 09:28:16.337  - [32minfo[39m: roomba.0 (9252) Adapter stopped und unloaded.
2024-04-05 09:28:16.338  - [32minfo[39m: roomba.0 (9252) terminating
2024-04-05 09:28:16.339  - [33mwarn[39m: roomba.0 (9252) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-04-05 09:28:16.340  - [32minfo[39m: roomba.0 (9252) State value to set for "roomba.0.states._connected" has to be type "string" but received type "boolean" 
2024-04-05 09:28:16.840  - [32minfo[39m: roomba.0 (9252) terminating
2024-04-05 09:28:16.909  - [31merror[39m: host.iobroker instance system.adapter.roomba.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-04-05 09:28:16.909  - [33mwarn[39m: host.iobroker Do not restart adapter system.adapter.roomba.0 because restart loop detected

**Comment by mcm1957** [comment]
Please add release version information to every problem reported:
- version of adapter:
- version of js-controller:
- nodeJS version installed:
- Operation system type / version:

**Comment by thesnoopy** [comment]
Hi,
as requested:

version of adapter: 1.2.2
version of js-controller: 5.0.19
nodeJS version installed: 18.20.1
Operation system type / version: Raspberry pi 5 with Debian GNU/Linux 12 (bookworm)
